### ISSUE TITLE
It's showing the error even if I did the tutorial

### ISSUE THREAD

**Issue by Briannewmc05** [jigsaw-4277821/PE-0.5-Android#10]
### Describe your problem here.

![Screenshot_20220115-142724](https://user-images.githubusercontent.com/96220748/149611951-12a47b59-762a-49a3-9632-32f98e148b95.png)
![Screenshot_20220115-142730](https://user-images.githubusercontent.com/96220748/149611954-ae27ed29-f785-4b2d-b6a3-348bdfefe88d.png)
![Screenshot_20220115-142735](https://user-images.githubusercontent.com/96220748/149611955-961489af-5935-45cc-b726-5bf00cf43bfa.png)
![Screenshot_20220115-142746](https://user-images.githubusercontent.com/96220748/149611956-f609fd7f-bcc7-4efd-957a-efbe1fd5358e.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CalypsoTH** [comment]
Does the assets and mods folder contain anything?

**Comment by Briannewmc05** [comment]
Yes, but I didn't put any mods in mods folder yet

**Comment by ZHyproX** [comment]
html5 build is no match for android so its so normal ı mean html5s targets are different.
